# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your Documentation
email: email@yourdomain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
doc_base_url: https://github.com/githubuser/githubrepo/
blog_url: https://blog.yourawesomeproject.com/
project_url: https://yourawesomeproject.com/
google_search_id: 001447907640164080602:dznp88ofbd0
twitter_username: twitteruser
github_username:  githubuser
disqus_id: ""

# Build settings
markdown: kramdown
